// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonicWarehouseManagement.Server.Data;

namespace SonicWarehouseManagement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201019023538_thirdcreate")]
    partial class thirdcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SonicWarehouseManagement.Shared.ArticleMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Article_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Article_Short_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assortment_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assortment_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Base_Unit_of_Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gross_Weight_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gross_Weight_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Listing_Module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merchandise_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Net_Weight_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Net_Weight_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primary_Price_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secondary_Price_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Conversion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Conversion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Conversion3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_CS_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_PC_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width_PC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Article_Masters");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.BusinessPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Banner_ID_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changed_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_On")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deactivation_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivering_Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivering_Site_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_Barangay_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_City_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_Level_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_Province_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lead_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAG_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Sub_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Sub_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PJP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfect_Store_Audit_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postal_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Search_Term1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Search_Term2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tax1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_of_Payment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_of_Payment_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAT_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eRTM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Business_Partners");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.ISR_DailySalesInvoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Aggr_Pieces")
                        .HasColumnType("int");

                    b.Property<string>("Billing_Type")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Billing_Type_1")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Cabinet_Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Calendar_Day")
                        .HasColumnType("datetime");

                    b.Property<int>("Coupon_Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("DT_Discount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Distributor_Desc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Free_Qty_Aggr_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_Aggr_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_Liter")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("GSV")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("Invoice_Due_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Invoice_No")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Lead_Basepack")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Basepack")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Basepack_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Brand")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Brand_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Master_FSS")
                        .HasColumnType("int");

                    b.Property<string>("Master_FSS_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Outlet_City")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Outlet_City_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Outlet_Subtype")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Master_Outlet_Subtype_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("NIV")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("Outlet_Code")
                        .HasColumnType("int");

                    b.Property<string>("Outlet_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Pack_Size")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Product_Id")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Purchase_Order_No")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Route_Desc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Sales_After")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Sales_Order_No")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Sales_Qty_Aggr_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_Aggr_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_Liter")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Sales_Route")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Salesman_Id")
                        .HasColumnType("int");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Salesman_Team_Type")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Salesman_Team_Type_Desc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Site_Desc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("TPR")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Terms_Of_Payment")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Total_Sales_Amnt_Inc")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UW")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Volume_Discount")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID");

                    b.ToTable("ISR_Daily_Sales_Invoices");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.InvoiceDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Aggr_Pieces")
                        .HasColumnType("int");

                    b.Property<int>("Cabinet_Count")
                        .HasColumnType("int");

                    b.Property<int>("Coupon_Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("DT_Discount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_Aggr_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_Aggr_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_Liter")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Free_Qty_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("GSV")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("Header_ID")
                        .HasColumnType("int");

                    b.Property<string>("Lead_Basepack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Basepack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Basepack_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Brand_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NIV")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Pack_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sales_After")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_Aggr_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_Aggr_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_CS")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_Liter")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Sales_Qty_PC")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TPR")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Total_Sales_Amnt_Inc")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UW")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Volume_Discount")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID");

                    b.ToTable("Invoice_Details");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.InvoiceHeaders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Billing_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Billing_Type_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Calendar_Day")
                        .HasColumnType("datetime2");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Invoice_Due_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Invoice_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Master_FSS")
                        .HasColumnType("int");

                    b.Property<string>("Master_FSS_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_City_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_Subtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_Subtype_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Outlet_Code")
                        .HasColumnType("int");

                    b.Property<string>("Outlet_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purchase_Order_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Order_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salesman_Id")
                        .HasColumnType("int");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Type_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_Of_Payment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Invoice_Headers");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.PurchaseDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Document_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Header_ID")
                        .HasColumnType("int");

                    b.Property<string>("Item_Code")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Posting_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Purchase_Details");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.PurchaseHeaders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article_Doc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Bill_Doc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Purchase_Headers");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.PurchaseOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article_Doc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Bill_Doc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Document_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Item_Code")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Posting_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Purchase_Orders");
                });

            modelBuilder.Entity("SonicWarehouseManagement.Shared.SalesmanMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_of_Birth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("End_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FSS_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FSS_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legacy_Salesman_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDA_Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDA_Flag_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Grp_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Route_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Type_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse_Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Salesman_Masters");
                });
#pragma warning restore 612, 618
        }
    }
}
